run:
  timeout: 5m
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  formats:
#    - format: json
#      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
  show-stats: false

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
#    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
#    - exhaustruct
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
#    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
#    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
#    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

  fast: true

issues:
  exclude-use-default: false
  exclude-case-sensitive: false
  new: true
  new-from-rev: HEAD
  whole-files: true
  fix: true
  exclude-rules:
    - text: "variable name 'ok' is too short for the scope of its usage"
      linters:
        - varnamelen
    - text: "type `validationError` is unused"
      linters:
        - unused
severity:
  default-severity: error
  case-sensitive: true
