package handlers

import (
	"github.com/thumbrise/validrator/internal/validation"
)

// BuiltInHandlers is the default pack of validations.
var BuiltInHandlers = map[string]validation.RuleHandlerFunc{
	"len":     Len,
	"boolean": Bool,
	// "required":                      hasValue,
	// "required_if":                   requiredIf,
	// "required_unless":               requiredUnless,
	// "skip_unless":                   skipUnless,
	// "required_with":                 requiredWith,
	// "required_with_all":             requiredWithAll,
	// "required_without":              requiredWithout,
	// "required_without_all":          requiredWithoutAll,
	// "excluded_if":                   excludedIf,
	// "excluded_unless":               excludedUnless,
	// "excluded_with":                 excludedWith,
	// "excluded_with_all":             excludedWithAll,
	// "excluded_without":              excludedWithout,
	// "excluded_without_all":          excludedWithoutAll,
	// "isdefault":                     isDefault,
	// "min":                           hasMinOf,
	// "max":                           hasMaxOf,
	// "eq":                            isEq,
	// "eq_ignore_case":                isEqIgnoreCase,
	// "ne":                            isNe,
	// "ne_ignore_case":                isNeIgnoreCase,
	// "lt":                            isLt,
	// "lte":                           isLte,
	// "gt":                            isGt,
	// "gte":                           isGte,
	// "eqfield":                       isEqField,
	// "eqcsfield":                     isEqCrossStructField,
	// "necsfield":                     isNeCrossStructField,
	// "gtcsfield":                     isGtCrossStructField,
	// "gtecsfield":                    isGteCrossStructField,
	// "ltcsfield":                     isLtCrossStructField,
	// "ltecsfield":                    isLteCrossStructField,
	// "nefield":                       isNeField,
	// "gtefield":                      isGteField,
	// "gtfield":                       isGtField,
	// "ltefield":                      isLteField,
	// "ltfield":                       isLtField,
	// "fieldcontains":                 fieldContains,
	// "fieldexcludes":                 fieldExcludes,
	// "alpha":                         isAlpha,
	// "alphanum":                      isAlphanum,
	// "alphaunicode":                  isAlphaUnicode,
	// "alphanumunicode":               isAlphanumUnicode,
	// "numeric":                       isNumeric,
	// "number":                        isNumber,
	// "hexadecimal":                   isHexadecimal,
	// "hexcolor":                      isHEXColor,
	// "rgb":                           isRGB,
	// "rgba":                          isRGBA,
	// "hsl":                           isHSL,
	// "hsla":                          isHSLA,
	// "e164":                          isE164,
	// "email":                         isEmail,
	// "url":                           isURL,
	//"http_url":                      isHttpURL,
	//"uri":                           isURI,
	//"urn_rfc2141":                   isUrnRFC2141, // RFC 2141
	//"file":                          isFile,
	//"filepath":                      isFilePath,
	//"base32":                        isBase32,
	//"base64":                        isBase64,
	//"base64url":                     isBase64URL,
	//"base64rawurl":                  isBase64RawURL,
	//"contains":                      contains,
	//"containsany":                   containsAny,
	//"containsrune":                  containsRune,
	//"excludes":                      excludes,
	//"excludesall":                   excludesAll,
	//"excludesrune":                  excludesRune,
	//"startswith":                    startsWith,
	//"endswith":                      endsWith,
	//"startsnotwith":                 startsNotWith,
	//"endsnotwith":                   endsNotWith,
	//"image":                         isImage,
	//"isbn":                          isISBN,
	//"isbn10":                        isISBN10,
	//"isbn13":                        isISBN13,
	//"issn":                          isISSN,
	//"eth_addr":                      isEthereumAddress,
	//"eth_addr_checksum":             isEthereumAddressChecksum,
	//"btc_addr":                      isBitcoinAddress,
	//"btc_addr_bech32":               isBitcoinBech32Address,
	//"uuid":                          isUUID,
	//"uuid3":                         isUUID3,
	//"uuid4":                         isUUID4,
	//"uuid5":                         isUUID5,
	//"uuid_rfc4122":                  isUUIDRFC4122,
	//"uuid3_rfc4122":                 isUUID3RFC4122,
	//"uuid4_rfc4122":                 isUUID4RFC4122,
	//"uuid5_rfc4122":                 isUUID5RFC4122,
	//"ulid":                          isULID,
	//"md4":                           isMD4,
	//"md5":                           isMD5,
	//"sha256":                        isSHA256,
	//"sha384":                        isSHA384,
	//"sha512":                        isSHA512,
	//"ripemd128":                     isRIPEMD128,
	//"ripemd160":                     isRIPEMD160,
	//"tiger128":                      isTIGER128,
	//"tiger160":                      isTIGER160,
	//"tiger192":                      isTIGER192,
	//"ascii":                         isASCII,
	//"printascii":                    isPrintableASCII,
	//"multibyte":                     hasMultiByteCharacter,
	//"datauri":                       isDataURI,
	//"latitude":                      isLatitude,
	//"longitude":                     isLongitude,
	//"ssn":                           isSSN,
	//"ipv4":                          isIPv4,
	//"ipv6":                          isIPv6,
	//"ip":                            isIP,
	//"cidrv4":                        isCIDRv4,
	//"cidrv6":                        isCIDRv6,
	//"cidr":                          isCIDR,
	//"tcp4_addr":                     isTCP4AddrResolvable,
	//"tcp6_addr":                     isTCP6AddrResolvable,
	//"tcp_addr":                      isTCPAddrResolvable,
	//"udp4_addr":                     isUDP4AddrResolvable,
	//"udp6_addr":                     isUDP6AddrResolvable,
	//"udp_addr":                      isUDPAddrResolvable,
	//"ip4_addr":                      isIP4AddrResolvable,
	//"ip6_addr":                      isIP6AddrResolvable,
	//"ip_addr":                       isIPAddrResolvable,
	//"unix_addr":                     isUnixAddrResolvable,
	//"mac":                           isMAC,
	//"hostname":                      isHostnameRFC952,  // RFC 952
	//"hostname_rfc1123":              isHostnameRFC1123, // RFC 1123
	//"fqdn":                          isFQDN,
	//"unique":                        isUnique,
	//"oneof":                         isOneOf,
	//"html":                          isHTML,
	//"html_encoded":                  isHTMLEncoded,
	//"url_encoded":                   isURLEncoded,
	//"dir":                           isDir,
	//"dirpath":                       isDirPath,
	//"json":                          isJSON,
	//"jwt":                           isJWT,
	//"hostname_port":                 isHostnamePort,
	//"lowercase":                     isLowercase,
	//"uppercase":                     isUppercase,
	//"datetime":                      isDatetime,
	//"timezone":                      isTimeZone,
	//"iso3166_1_alpha2":              isIso3166Alpha2,
	//"iso3166_1_alpha2_eu":           isIso3166Alpha2EU,
	//"iso3166_1_alpha3":              isIso3166Alpha3,
	//"iso3166_1_alpha3_eu":           isIso3166Alpha3EU,
	//"iso3166_1_alpha_numeric":       isIso3166AlphaNumeric,
	//"iso3166_1_alpha_numeric_eu":    isIso3166AlphaNumericEU,
	//"iso3166_2":                     isIso31662,
	//"iso4217":                       isIso4217,
	//"iso4217_numeric":               isIso4217Numeric,
	//"bcp47_language_tag":            isBCP47LanguageTag,
	//"postcode_iso3166_alpha2":       isPostcodeByIso3166Alpha2,
	//"postcode_iso3166_alpha2_field": isPostcodeByIso3166Alpha2Field,
	//"bic":                           isIsoBicFormat,
	//"semver":                        isSemverFormat,
	//"dns_rfc1035_label":             isDnsRFC1035LabelFormat,
	//"credit_card":                   isCreditCard,
	//"cve":                           isCveFormat,
	//"luhn_checksum":                 hasLuhnChecksum,
	//"mongodb":                       isMongoDB,
	//"cron":                          isCron,
	//"spicedb":                       isSpiceDB,
}
